variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_BUILD: $CI_REGISTRY_IMAGE/builds:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
   - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

stages:
  - build

build:
  stage: build
  script:
    - echo $IMAGE_TAG
    - echo $IMAGE_TAG_BUILD

    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_BUILD -f Dockerfile.build .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_BUILD
