FROM node:12.12.0-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i

COPY . ./
RUN GENERATE_SOURCEMAP=false npm run build

FROM nginx:1.13.0-alpine
RUN mkdir -p /app
WORKDIR /app
COPY --from=0 /app/dist ./
COPY ./docker/nginx/admin.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
